# Generated by Django 2.1.7 on 2019-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatName',
            field=models.CharField(max_length=100),
        ),
    ]
