# Generated by Django 2.1.7 on 2019-03-27 14:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190326_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatName',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=255, null=True), max_length=255, size=None),
        ),
    ]
