# Generated by Django 2.1.7 on 2019-03-24 21:23

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190324_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatName',
            field=django_mysql.models.EnumField(choices=[('World', 'World'), ('Naija', 'Naija'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Travel', 'Travel')]),
        ),
    ]
