# Generated by Django 2.1.7 on 2019-03-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190327_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='deyCategory',
            new_name='category',
        ),
    ]
