# Generated by Django 2.1.7 on 2019-03-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deyCategory',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='deyCategory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
